package instruction_pkg;

typedef enum logic[0:2] {
    RR,
    RRR,
    RI7,
    RI10,
    RI16,
    RI18
}  instruction_type;


typedef enum logic[0:6] {
    OP_ADD_WORD,
    OP_ADD_HALFWORD,
    OP_ADD_EXTENDED,
    OP_SUBTRACT_FROM_WORD,
    OP_SUBTRACT_FROM_HALFWORD,
    OP_SUBTRACT_FROM_EXTENDED,
    OP_CARRY_GENERATE,
    OP_BORROW_GENERATE,
    OP_ADD_WORD_IMMEDIATE,
    OP_ADD_HALFWORD_IMMEDIATE,
    OP_SUBTRACT_FROM_WORD_IMMEDIATE,
    OP_SUBTRACT_FROM_HALFWORD_IMMEDIATE,
    OP_COUNT_LEADING_ZEROS,
    OP_FORM_SELECT_MASK_FOR_HALFWORDS,
    OP_FORM_SELECT_MASK_FOR_WORDS,
    OP_AND,
    OP_AND_WORD_IMMEDIATE,
    OP_AND_HALFWORD_IMMEDIATE,
    OP_OR,
    OP_OR_WORD_IMMEDIATE,
    OP_OR_HALFWORD_IMMEDIATE,
    OP_EXCLUSIVE_OR,
    OP_EXCLUSIVE_OR_WORD_IMMEDIATE,
    OP_EXCLUSIVE_OR_HALFWORD_IMMEDIATE,
    OP_NAND,
    OP_NOR,
    OP_COMPARE_EQUAL_WORD,
    OP_COMPARE_EQUAL_HALFWORD,
    OP_COMPARE_GREATER_THAN_WORD,
    OP_COMPARE_GREATER_THAN_HALFWORD,
    OP_COMPARE_LOGICAL_GREATER_THAN_WORD,
    OP_COMPARE_LOGICAL_GREATER_THAN_HALFWORD,
    OP_COMPARE_EQUAL_WORD_IMMEDIATE,
    OP_COMPARE_EQUAL_HALFWORD_IMMEDIATE,
    OP_COMPARE_GREATER_THAN_WORD_IMMEDIATE,
    OP_COMPARE_GREATER_THAN_HALFWORD_IMMEDIATE,
    OP_COMPARE_LOGICAL_GREATER_THAN_WORD_IMMEDIATE,
    OP_COMPARE_LOGICAL_GREATER_THAN_HALFWORD_IMMEDIATE,
    OP_IMMEDIATE_LOAD_WORD,
    OP_IMMEDIATE_LOAD_HALFWORD,
    OP_IMMEDIATE_LOAD_ADDRESS,
    OP_IMMEDIATE_LOAD_HALFWORD_UPPER,
    OP_IMMEDIATE_OR_HALFWORD_LOWER,
    OP_SHIFT_LEFT_WORD,
    OP_SHIFT_LEFT_HALFWORD,
    OP_SHIFT_LEFT_WORD_IMMEDIATE,
    OP_SHIFT_LEFT_HALFWORD_IMMEDIATE,
    OP_ROTATE_WORD,
    OP_ROTATE_HALFWORD,
    OP_ROTATE_WORD_IMMEDIATE,
    OP_ROTATE_HALFWORD_IMMEDIATE,
    OP_ROTATE_AND_MASK_WORD,
    OP_ROTATE_AND_MASK_HALFWORD,
    OP_ROTATE_AND_MASK_ALGEBRAIC_WORD,
    OP_ROTATE_AND_MASK_ALGEBRAIC_HALFWORD,
    OP_MULTIPLY,
    OP_MULTIPLY_UNSIGNED,
    OP_MULTIPLY_IMMEDIATE,
    OP_MULTIPLY_UNSIGNED_IMMEDIATE,
    OP_MULTIPLY_AND_ADD,
    OP_FLOATING_ADD,
    OP_FLOATING_SUBTRACT,
    OP_FLOATING_MULTIPLY,
    OP_FLOATING_MULTIPLY_AND_ADD,
    OP_FLOATING_NEGATIVE_MULTIPLY_AND_SUBTRACT,
    OP_FLOATING_MULTIPLY_AND_SUBTRACT,
    OP_FLOATING_COMPARE_EQUAL,
    OP_FLOATING_COMPARE_MAGNITUDE_EQUAL,
    OP_FLOATING_COMPARE_GREATER_THAN,
    OP_FLOATING_COMPARE_MAGNITUDE_GREATER_THAN,
    OP_AVERAGE_BYTES,
    OP_SUM_BYTES_INTO_HALFWORDS,
    OP_ABSOLUTE_DIFFERENCES_OF_BYTES,
    OP_COUNT_ONES_IN_BYTES,
    OP_SHIFT_LEFT_QUADWORD_BY_BYTES,
    OP_SHIFT_LEFT_QUADWORD_BY_BYTES_IMMEDIATE,
    OP_SHIFT_LEFT_QUADWORD_BY_BITS,
    OP_ROTATE_QUADWORD_BY_BYTES,
    OP_ROTATE_QUADWORD_BY_BYTES_IMMEDIATE,
    OP_ROTATE_QUADWORD_BY_BITS,
    OP_ROTATE_AND_MASK_QUADWORD_BY_BYTES,
    OP_LOAD_QUADWORD_X,
    OP_LOAD_QUADWORD_D,
    OP_LOAD_QUADWORD_A,
    OP_STORE_QUADWORD_X,
    OP_STORE_QUADWORD_D,
    OP_STORE_QUADWORD_A,
    OP_BRANCH_RELATIVE,
    OP_BRANCH_ABSOLUTE,
    OP_BRANCH_INDIRECT,
    OP_BRANCH_RELATIVE_AND_SET_LINK,
    OP_BRANCH_ABSOLUTE_AND_SET_LINK,
    OP_BRANCH_INDIRECT_AND_SET_LINK,
    OP_BRANCH_IF_ZERO_WORD,
    OP_BRANCH_IF_ZERO_HALFWORD,
    OP_BRANCH_IF_NOT_ZERO_WORD,
    OP_BRANCH_IF_NOT_ZERO_HALFWORD,
    OP_BRANCH_INDIRECT_IF_ZERO,
    OP_BRANCH_INDIRECT_IF_ZERO_HALFWORD,
    OP_BRANCH_INDIRECT_IF_NOT_ZERO,
    OP_BRANCH_INDIRECT_IF_NOT_ZERO_HALFWORD,
    OP_NO_OP_EVEN,
    OP_NO_OP_ODD,
    OP_NO_OP_HARDWARE
} opcode_t;


typedef struct packed {
    logic[0:2] unit_id;
    logic[0:127] result;
    logic[0:6] reg_write_addr;
    logic[0:3] ready_stage_number;
    logic reg_write_flag;
    logic present_bit;
    logic[0:3] current_stage_number;
    logic[0:31] branch_addr;
} unit_result_packet;



endpackage